# ================= DATABASE =================
# ================= DATABASE =================

# Database connection URL (which database to connect to)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}

# Database username
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}

# Database password
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mypassword}

# JDBC driver class used to connect PostgreSQL
# Responsibility of drive
# Open DB connection (create connection)
#Send SQL query and Receive result
spring.datasource.driver-class-name=org.postgresql.Driver

# Generate SQL compatible with PostgreSQL
# (because every database has slightly different SQL syntax)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Automatically update database tables based on entity changes
spring.jpa.hibernate.ddl-auto=update

# Show executed SQL queries in logs
spring.jpa.show-sql=false

# ================= REDIS =================
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:myredispassword}

spring.data.redis.database=0
spring.data.redis.timeout=60000ms
spring.data.redis.jedis.pool.max-active=8
spring.data.redis.jedis.pool.max-idle=8
spring.data.redis.jedis.pool.min-idle=0
spring.data.redis.jedis.pool.max-wait=2000ms

# ================= JWT =================
auth.jwt.secret=${AUTH_JWT_SECRET:q83JfL9k2Jd8sK3l9Kf7sP2lK8s9dJ3lK2l8sJf9sL0=}
auth.jwt.access-token-validity=${AUTH_JWT_ACCESS_TOKEN_VALIDITY:900000}

# ================= SERVER =================
spring.application.name=AUTH-SERVICE
server.port=8081
server.error.include-message=always
server.error.include-binding-errors=always

# ================= EUREKA =================
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
