services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - microservices-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    env_file:
      - ./.env
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    networks:
      - microservices-network
    restart: on-failure

  user-management-service:
    build:
      context: ./user-management-service
      dockerfile: Dockerfile
    container_name: user-management-service
    env_file:
      - ./.env
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - redis
    networks:
      - microservices-network
    restart: on-failure

volumes:
  postgres_data:
  redis_data:

networks:
  microservices-network:
    driver: bridge
